
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  build_and_push:
    name: "Build and push"
    runs-on: ubuntu-latest
    steps:
      -
        name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
      - 
        name: Login
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.DOCKER_REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        name: Build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ github.repository }}:${{ steps.get_version.outputs.VERSION }}

